apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki-gateway
    app.kubernetes.io/part-of: k8s-playground
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
