apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loki-gateway
  ports:
    - name: https
      port: 443
      targetPort: https
      appProtocol: https
