apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-playground-service
  namespace: k8s-playground-service
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/name: k8s-playground-service
    app.kubernetes.io/part-of: k8s-playground
