apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir-gateway
  labels:
    app.kubernetes.io/name: mimir-gateway
    app.kubernetes.io/part-of: k8s-playground
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
