apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: alloy-otlp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: k8s-playground
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/k8s-playground-service/sa/k8s-playground-service
      to:
        - operation:
            ports:
              - "4318"
            methods:
              - POST
            paths:
              - /v1/metrics
              - /v1/traces
