apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: alloy-otlp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: k8s-playground
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  portLevelMtls:
    "4318":
      mode: STRICT
